POST http://localhost:8080/dream/goods/saveGoods
Accept: */*
Content-Type: application/json;charset=utf-8

{
  "goodsName": "小米电视2",
  "goodsPrice": 1999.99,
  "goodsStatus": 0,
  "description": "品牌是个好品牌",
  "userId": "772003356",
  "userName": "wyw"
}

###